name: Build resume PDF
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF
        run: wkhtmltopdf --enable-local-file-access index.html resume.pdf

      - name: Commit PDF
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-build resume PDF"
          file_pattern: resume.pdf
